# Generated by Guarantee_Agent from a successful Markdown run.
import os

from playwright.sync_api import Page, expect


def test_generated(page: Page) -> None:
    page.goto(os.environ.get("AUTOQA_BASE_URL", "/"))
    # Step 1: 打开 http://127.0.0.1:18090
    # Action was executed by the AutoQA agent during recording.
    # Step 2: 验证页面上能看到 "Example Domain" 文字
    expect(page.get_by_text("Example Domain").first).to_be_visible()


if __name__ == "__main__":
    from playwright.sync_api import sync_playwright
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        test_generated(page)
        browser.close()
