# Generated by Guarantee_Agent from a successful Markdown run.
import os

from playwright.sync_api import Page, expect


def test_generated(page: Page) -> None:
    page.goto(os.environ.get("AUTOQA_BASE_URL", "/"))
    # Step 1: 打开 http://127.0.0.1:18090/form.html
    # Action was executed by the AutoQA agent during recording.
    # Step 2: 断言标题元素 "AutoQA Form Fixture" 可见
    expect(page.get_by_text("AutoQA Form Fixture").first).to_be_visible()
    # Step 3: 在 Username 输入框填写 "alice"
    # Action was executed by the AutoQA agent during recording.
    # Step 4: 在 Favorite color 下拉框选择 Green
    # Action was executed by the AutoQA agent during recording.
    # Step 5: 点击 Submit 按钮
    expect(page.get_by_text("Form submitted successfully").first).to_be_visible()
    # Step 6: 向下滚动页面
    # Action was executed by the AutoQA agent during recording.
    # Step 7: 验证 "You reached the bottom" 文字可见
    expect(page.get_by_text("You reached the bottom").first).to_be_visible()
    # Step 8: 点击 Show After Wait 按钮
    # Action was executed by the AutoQA agent during recording.
    # Step 9: 等待 1000 毫秒
    # Action was executed by the AutoQA agent during recording.
    # Step 10: 验证 "Visible after wait" 文字可见
    expect(page.get_by_text("Visible after wait").first).to_be_visible()


if __name__ == "__main__":
    from playwright.sync_api import sync_playwright
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        test_generated(page)
        browser.close()
