package runner

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"guarantee-agent/internal/markdown"
)

// ExportPlaceholder 为一次成功 run 写出 Playwright 风格的 Python 用例文件(pytest)。
//
// 每个 Markdown 步骤生成一段带注释的步骤块:带 Expected 子句或断言步骤生成
// expect(...).to_be_visible,纯动作步骤生成注释占位(具体定位器应由更完整的 IR 记录器提供)。
// 生成的文件是有意保持可运行的样板,用以文档化本次 run。
func ExportPlaceholder(cwd, exportDir, specPath string, spec *markdown.Spec) error {
	if exportDir == "" {
		exportDir = "tests/autoqa"
	}
	if err := os.MkdirAll(filepath.Join(cwd, exportDir), 0755); err != nil {
		return err
	}
	// pytest 要求测试文件以 test_ 开头。
	name := "test_" + sanitize(strings.TrimSuffix(filepath.Base(specPath), filepath.Ext(specPath))) + ".py"
	path := filepath.Join(cwd, exportDir, name)

	var b strings.Builder
	b.WriteString("# Generated by Guarantee_Agent from a successful Markdown run.\n")
	b.WriteString("import os\n\n")
	b.WriteString("from playwright.sync_api import Page, expect\n\n\n")

	title := spec.Title
	if title == "" {
		title = strings.TrimSuffix(filepath.Base(specPath), filepath.Ext(specPath))
	}
	fmt.Fprintf(&b, "def %s(page: Page) -> None:\n", pyFuncName(title))
	b.WriteString("    page.goto(os.environ.get(\"AUTOQA_BASE_URL\", \"/\"))\n")
	for _, step := range spec.Steps {
		fmt.Fprintf(&b, "    # Step %d: %s\n", step.Index, step.Text)
		switch {
		case step.ExpectedResult != "":
			fmt.Fprintf(&b, "    expect(page.get_by_text(%s).first).to_be_visible()\n", pyStr(step.ExpectedResult))
		case step.Kind == markdown.StepKindAssertion:
			fmt.Fprintf(&b, "    expect(page.get_by_text(%s).first).to_be_visible()\n", pyStr(exportAssertionTarget(step.Text)))
		default:
			b.WriteString("    # Action was executed by the AutoQA agent during recording.\n")
		}
	}
	b.WriteString("\n\nif __name__ == \"__main__\":\n")
	fmt.Fprintf(&b, "    from playwright.sync_api import sync_playwright\n")
	fmt.Fprintf(&b, "    with sync_playwright() as p:\n")
	fmt.Fprintf(&b, "        browser = p.chromium.launch()\n")
	fmt.Fprintf(&b, "        page = browser.new_page()\n")
	fmt.Fprintf(&b, "        %s(page)\n", pyFuncName(title))
	fmt.Fprintf(&b, "        browser.close()\n")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

// pyStr 把字符串转成 Python 双引号字面量,转义其中的反斜杠和双引号。
func pyStr(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return "\"" + s + "\""
}

// pyFuncName 把标题转成合法的 Python 函数名(test_<snake_case>)。
func pyFuncName(title string) string {
	s := "test_" + sanitize(title)
	// sanitize 已转成小写连字符,这里再转成下划线,并补齐 test_ 前缀。
	s = strings.ReplaceAll(s, "-", "_")
	if s == "test_" {
		s = "test_generated"
	}
	return s
}

// sanitize 把字符串转小写,并用单个连字符替换非字母数字的连续字符,
// 以生成文件系统安全的测试文件名。
func sanitize(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	lastDash := false
	for _, r := range s {
		ok := (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')
		if ok {
			b.WriteRune(r)
			lastDash = false
		} else if !lastDash {
			b.WriteByte('-')
			lastDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

// exportAssertionTarget 从断言步骤文本里抽取要断言的目标文本,尽量与运行时
// AI 实际断言的文本对齐。规则:
//   - 先去掉 Verify/Assert/验证/断言 前缀;
//   - 若剩余文本含引号("..."或“...”),优先取第一段引号内内容(用例里断言目标
//     通常写在引号里,如 验证...能看到 "Example Domain" 文字);
//   - 否则去掉常见可见性后缀(text is visible / 可见 等)后用整句。
func exportAssertionTarget(s string) string {
	s = strings.TrimSpace(s)
	for _, p := range []string{"Verify", "Assert", "验证", "断言"} {
		s = strings.TrimPrefix(s, p)
	}
	s = strings.TrimSpace(s)
	// 优先取引号内内容(支持中英文引号)。
	if q := firstQuoted(s); q != "" {
		return q
	}
	for _, suffix := range []string{" text is visible", " is visible", " text exists", " exists", "可见", "存在"} {
		s = strings.TrimSuffix(s, suffix)
	}
	return strings.TrimSpace(s)
}

// firstQuoted 返回 s 中第一段被引号包裹的内容(支持 "..."、“...” 和 '...'),没有则返回 ""。
func firstQuoted(s string) string {
	for _, pair := range [][2]string{{`"`, `"`}, {"“", "”"}, {"'", "'"}} {
		l, r := pair[0], pair[1]
		i := strings.Index(s, l)
		if i < 0 {
			continue
		}
		rest := s[i+len(l):]
		j := strings.Index(rest, r)
		if j < 0 {
			continue
		}
		return strings.TrimSpace(rest[:j])
	}
	return ""
}
