package runner

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"guarantee-agent/internal/markdown"
)

// ExportPlaceholder 为一次成功 run 写出 Playwright 风格的用例文件。
//
// 每个 Markdown 步骤生成一个 test.step:带 Expected 子句或断言步骤生成
// expect(...).toBeVisible,纯动作步骤生成注释占位(具体定位器应由更完整的 IR 记录器提供)。
// 生成的文件是有意保持可运行的样板,用以文档化本次 run。
func ExportPlaceholder(cwd, exportDir, specPath string, spec *markdown.Spec) error {
	if exportDir == "" {
		exportDir = "tests/autoqa"
	}
	if err := os.MkdirAll(filepath.Join(cwd, exportDir), 0755); err != nil {
		return err
	}
	name := sanitize(strings.TrimSuffix(filepath.Base(specPath), filepath.Ext(specPath))) + ".spec.ts"
	path := filepath.Join(cwd, exportDir, name)
	var b strings.Builder
	b.WriteString("import { test, expect } from '@playwright/test'\n\n")
	title := spec.Title
	if title == "" {
		title = strings.TrimSuffix(filepath.Base(specPath), filepath.Ext(specPath))
	}
	fmt.Fprintf(&b, "test(%q, async ({ page }) => {\n", title)
	b.WriteString("  // Generated by Guarantee_Agent from a successful Markdown run.\n")
	b.WriteString("  await page.goto(process.env.AUTOQA_BASE_URL || '/');\n")
	for _, step := range spec.Steps {
		fmt.Fprintf(&b, "  await test.step(%q, async () => {\n", step.Text)
		if step.ExpectedResult != "" {
			fmt.Fprintf(&b, "    await expect(page.getByText(%q).first()).toBeVisible();\n", step.ExpectedResult)
		} else if step.Kind == markdown.StepKindAssertion {
			fmt.Fprintf(&b, "    await expect(page.getByText(%q).first()).toBeVisible();\n", exportAssertionTarget(step.Text))
		} else {
			b.WriteString("    // Action was executed by the AutoQA agent during recording.\n")
		}
		b.WriteString("  });\n")
	}
	b.WriteString("});\n")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

// sanitize 把字符串转小写,并用单个连字符替换非字母数字的连续字符,
// 以生成文件系统安全的测试文件名。
func sanitize(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	lastDash := false
	for _, r := range s {
		ok := (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')
		if ok {
			b.WriteRune(r)
			lastDash = false
		} else if !lastDash {
			b.WriteByte('-')
			lastDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

// exportAssertionTarget 与 agent.assertionTarget 保持一致:去掉 Verify/Assert
// 前缀和常见可见性后缀,使导出的测试断言与运行时实际断言的文本对齐。
func exportAssertionTarget(s string) string {
	s = strings.TrimSpace(s)
	for _, p := range []string{"Verify", "Assert", "验证", "断言"} {
		s = strings.TrimPrefix(s, p)
	}
	s = strings.TrimSpace(s)
	for _, suffix := range []string{" text is visible", " is visible", " text exists", " exists", "可见", "存在"} {
		s = strings.TrimSuffix(s, suffix)
	}
	return strings.TrimSpace(s)
}
